### ISSUE TITLE
Improve Roles.yaml

### ISSUE THREAD

**Issue by crystaldeveloper2017** [crystaldeveloper2017/Frameworkpackage#48]
In Roles.yaml, whenever we add a action, element in an existing role, github does not understand / display the difference properly.

To overcome this, we should improve the roles.yaml file
Current Example
```
- roleId: 16
  roleName: "AttendantFuel"
  actions: getVehicleIdForCustomer, acceptPhonePayPayment,showPhonePePayments,changePassword,showChangePassword,generateDailyInvoiceReport,showCheckInScreen,showHomePage,checkInNozzle,showGenerateInvoice,checkOutNozzle,showCheckOutScreen,showAddTestFuel,addTestFuel,showUnclaimedPayments,showUserRoleMapping,showUserDetails
  elements: 700165,700190,700168,21,7,700180,700195,700197,700178,26
```

Improved Approach
```
- roleId: 16
  roleName: "AttendantFuel"
  actions:
  - getVehicleIdForCustomer
  - acceptPhonePayPayment
  - showPhonePePayments
  - changePassword
  elements: 
   - 700165
   - 700190 
   - 21
   - 7001687
```

Another Approach would be that each role will have its own file instead of the single file for all roles
